### PR TITLE
Export `HandlerFunction`

### PR DESCRIPTION
**Pull request by JuanM04**

### CODE REVIEW

**Comment by wolfy1339** [comment]
Hi @JuanM04 :wave:,

Can you explain the reasoning behind your changes?

**Comment by JuanM04** [comment]
I was trying to create a handler with TypeScript and `probot`. The only type I couldn't import was this one

**Comment by wolfy1339** [comment]
I see

**Comment by wolfy1339** [comment]
However, you can import it this way:
```ts
import { HandlerFunction } from "@octokit/webhooks/dist-types/types"
```

**Comment by JuanM04** [comment]
Hmm.. I didn't think about that.

That works for me. If you want, you can close this PR

**Comment by gr2m** [comment]
> ```ts
> import { HandlerFunction } from "@octokit/webhooks/dist-types/types"
> ```

I wouldn't consider this public API though. If you import from a path within the package I'd suggest you pin the version. We don't currently plan on it but we might change the structure of the published package in future, at which point the above line would break. And this would be an internal change that would not require a breaking version release, it could happen in a fix version bump

**Pull request closed without merging**
