### PR TITLE
feat: reply after 9s with 202 status

### LINKED ISSUE #185: Make sure to respond within 10s in `.middleware`
> GitHub expects that integrations respond within 10 seconds of receiving the webhook payload. If your service takes longer than that to complete, then GitHub terminates the connection and the payload is lost.

https://docs.github.com/en/rest/guides/best-practices-for-integrators#favor-asynchronous-work-over-synchronous

We currently await the handling of all event handlers.

I think what we should do instead is to start a timer for 9s. If it runs out before the event handlers are done, respond with a [`202` status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202)

The change would need to be implemented here:
https://github.com/octokit/webhooks.js/blob/aee3e94ae9450bee88c78eb073696a176913a542/src/middleware/middleware.ts#L48-L67

### PR DESCRIPTION
**Pull request by gr2m**
We can test this with https://github.com/sinonjs/fake-timers, without needing to wait for 10s in our tests.

If anynone wants to finish this today be my guest, if not I'll finish this up tomorrow

fixes #185

### CODE REVIEW

**Comment by oscard0m** [comment]
This PR fixes #185 right?

**Comment by gr2m** [comment]
> This PR fixes #185 right?

Yes 👍🏼 

> if not I'll finish this up tomorrow

I think it makes sense to finish up the rewrite of the tests to Jest & TypeScript first :)

**Comment by gr2m** [comment]
I'll have to finish this on Friday latest. It might create some merge conflicts with your work on rewriting tests to TypeScript I'm afraid, but I need to finish up Probot v10 and this will become a blocker by then

**Comment by oscard0m** [comment]
> I'll have to finish this on Friday latest. It might create some merge conflicts with your work on rewriting tests to TypeScript I'm afraid, but I need to finish up Probot v10 and this will become a blocker by then

From my side it's fine. I will be with no laptop for the next to weeks. I would ask to @wolfy1339

**Pull request merged**
