### PR TITLE
refactor(typescript): simplify TransformMethod type

### PR DESCRIPTION
**Pull request by jablko**
Can we simplify the `TransformMethod` type as follows?
```Diff
-type TransformMethod<T extends EmitterWebhookEvent, V = T> = (
+type TransformMethod<T> = (
   event: EmitterWebhookEvent
-) => V | PromiseLike<V>;
+) => T | PromiseLike<T>;
```

### CODE REVIEW

**Review by gr2m — DISMISSED** [review]
Looks good to me! I'm always a bit nervous about TypeScript changes though, and given that we just broke `@octokit/webhooks` for some TypeScript users, I'd appreciate a 2nd review

**Review by G-Rath — DISMISSED** [review]

**Comment by G-Rath** [comment]
@gr2m this should be fine - the reason I didn't originally do this was for similar reasons: lack of familiarity with the codebase + didn't want to make too many waves all at once :)

(in fact this might fix the issue in `@octokit/app.js`)

**Comment by G-Rath** [comment]
(thinking about it, this is probably meant to be `event: T`, but I can't think of a situation where that'd improve things - worse case we can adjust the type later 🤷)

**Review by gr2m — APPROVED** [review]
Thanks @G-Rath! I resolved the merge conflict which invalidated your review, but this is good to merge now as soon as CI is happy

**Comment by gr2m** [comment]
I've merged it as a fix so that users will get the new version, in case something blows up it will be easier to track down and revert

**Pull request merged**
