### PR TITLE
build(typescript): add noUnusedLocals and noUnusedParameters to tsconfig.json

### LINKED ISSUE #287: What about integrating ESLint in the project?
I was thinking on avoiding future clean code issues like unused variables (i.e. https://github.com/octokit/webhooks.js/pull/285) but I would like to know first what are your thoughts on Linting the project

### PR DESCRIPTION
**Pull request by oscard0m**
## 📝 Summary

Add the following properties to `tsconfig.json`:
* `noUnusedLocals`
* `noUnusedParameters`

## ⛱ Motivation and Context

Fix #287 

## 📊 How Has This Been Tested?

Run `npm run build` with an unused variable to make sure the compilation fails

## 📚 References:

* https://www.typescriptlang.org/tsconfig#noUnusedLocals
* https://www.typescriptlang.org/tsconfig#noUnusedParameters

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Looks good, thank you!

**Comment by gr2m** [comment]
I wonder if I should create an `octokit/tsconfig` repository, to have a central configuration for all `@octokit/*` modules. Similar to https://www.npmjs.com/package/@tsconfig/node10. What do you think? Do you see any problems with it?

**Comment by oscard0m** [comment]
> I wonder if I should create an `octokit/tsconfig` repository, to have a central configuration for all `@octokit/*` modules. Similar to [npmjs.com/package/@tsconfig/node10](https://www.npmjs.com/package/@tsconfig/node10). What do you think? Do you see any problems with it?

I was thinking exactly the same. To me has sense. What do you think @wolfy1339 ?

**Comment by wolfy1339** [comment]
I don't see any problems

**Comment by gr2m** [comment]
`@octokit/tsconfig` is out now. I also added you as contributors to the octokit/tsconfig repository so you can go ahead fix bugs if you like :)

**Pull request merged**
