### PR TITLE
chore: explicitly mark imports/exports that are only used as types

### PR DESCRIPTION
**Pull request by wolfy1339**
----

### Before the change?

* Some compilers that don't fully parse typescript, ex: Babel and esbuild, would include these imports/exports in the build output

### After the change?

* With the explicit markers, those imports/exports aren't included in the build output

### Other information

*

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]

**Comment by oscard0m** [comment]
Should we lint this? https://typescript-eslint.io/rules/consistent-type-imports/ @wolfy1339

**Comment by wolfy1339** [comment]
It would be nice, but i don't think introducing another linter is the best idea

**Comment by oscard0m** [comment]
> It would be nice, but i don't think introducing another linter is the best idea

Some extra step in test.yml maybe? Still creates friction to contributors, right?

**Comment by wolfy1339** [comment]
If it were a plugin for prettier, it would work just fine. Introducing eslint into the mix is probably not the best call.

For now, it will just have to be something to watch out for

**Pull request merged**
