### PR TITLE
feat: new Webhooks events (pull_request.auto_merge_{enable,disable})

### PR DESCRIPTION
**Pull request by octokitbot**
A new release of [@octokit/webhooks](https://github.com/octokit/webhooks) was just released 👋🤖

This pull request updates the TypeScript definitions derived from `@octokit/webhooks`. I can't tell if the changes are fixes, features or breaking, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

-----
[View rendered README.md](https://github.com/octokit/webhooks.js/blob/update-octokit-webhooks/README.md)

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]

**Comment by wolfy1339** [comment]
I created a manual release since the commit message was wrong, and didn't trigger the automatic release

**Comment by wolfy1339** [comment]
@gr2m It will have to be pushed to npm manually
@G-Rath `npm run build` fails
```
../../../node_modules/@types/express-serve-static-core/index.d.ts(223,18): error TS2430: Interface 'Request<P, ResBody, ReqBody, ReqQuery>' incorrectly extends interface 'IncomingMessage'.
  Types of property 'body' are incompatible.
    Type 'ReqBody' is not assignable to type 'CheckRunCompletedEvent | CheckRunCreatedEvent | CheckRunRequestedActionEvent | CheckRunRerequestedEvent | ... 161 more ... | undefined'.
      Type 'ReqBody' is not assignable to type 'WorkflowRunRequestedEvent'.
```

**Comment by G-Rath** [comment]
But we're not pulling in that package...

```
webhooks.js on  master is 📦 v0.0.0-development took 7s
❯ npm ls @types/express-serve-static-core
@octokit/webhooks@0.0.0-development /c/Users/G-Rath/workspace/projects-oss/webhooks.js
└── (empty)
```

If you're running locally, make sure you've done `npm install` to ensure you've got the latest packages (specifically in this case, to make sure you've not got `@types/express` since we removed that as a dependency).

**Comment by wolfy1339** [comment]
I nuked my `node_modules` folder, and ran `npm install` and i get the same result

**Comment by wolfy1339** [comment]
It seems it picked it up higher up (from my home directory)

**Comment by G-Rath** [comment]
> It seems it picked it up higher up (from my home directory)

That shouldn't happen - TypeScript shouldn't go wandering up the directory tree unless something else is very wrong 🤔
(in saying that, it could be `pika` doing something funny?)

What's the output of:
  * `npm ls @types/express-serve-static-core`
  * `which tsc` (if you're on linux, otherwise `where tsc` for Windows)
  * `npm ls -g`

**Comment by wolfy1339** [comment]
* `npm ls @types/express-serve-static-core`

```
$ npm ls @types/express-serve-static-core
@octokit/webhooks@0.0.0-development /home/thomas/Desktop/Programming/webhooks.js
└── (empty)
```

* `which tsc`: no output; I don't have `node_modules/.bin` in my `PATH`
* `npm ls -g`

```
$ npm ls -g
/usr/lib
└── npm@7.5.1
```

**Comment by G-Rath** [comment]
That's interesting.

So `npm@7` installs `peerDependencies` by default, which means we could be pulling in some new dependencies that'd include the package, but I'd expect it to show in `npm ls`... 🤔

**Pull request merged**
