### PR TITLE
fix: bump `@octokit/webhooks-methods` to `^2.0.0`

### PR DESCRIPTION
**Pull request by gr2m**
follow up to https://github.com/octokit/webhooks-methods.js/pull/21

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]

**Comment by rr-codes** [comment]
@wolfy1339 This is a breaking change, and led to all my GitHub payloads breaking. This is because `@octokit/webhooks-methods` had a breaking change requiring the payloads to be `string` instead of JSON objects, both of which worked fine until this PR, and now only `string` works.

**Comment by rr-codes** [comment]
for context, I am using Express, and had this middleware:


```js
app.use((req, res, next) => {
  if (req.originalUrl.includes('/stripe/webhook')) {
    bodyParser.raw({ type: 'application/json' })(req, res, next);
  } else {
    bodyParser.json()(req, res, next);
  }
});
```

However, with this PR, I had to change it to
```js
app.use((req, res, next) => {
  if (req.originalUrl.includes('/stripe/webhook')) {
    bodyParser.raw({ type: 'application/json' })(req, res, next);
  } else if (req.originalUrl.includes('/webhooks/github')) {
    bodyParser.text({ type: 'application/json' })(req, res, next);
  } else {
    bodyParser.json()(req, res, next);
  }
});
```

**Comment by wolfy1339** [comment]
It was a breaking change in the `@octokit/webhools-methods` package, we added a compatibility layer to this package in the meantime until the change is implemented in this package as well.

**Comment by rr-codes** [comment]
@wolfy1339 Ya I saw the changes, but the compatibility layer didn't seem to have any effect

**Comment by wolfy1339** [comment]
Could you open a new issue with all the details, and we can start looking from there

**Comment by rr-codes** [comment]
sure, will do

**Pull request merged**
