### PR TITLE
feat(types): use OpenAPI spec

### LINKED ISSUE #840: Adapt the types to the OpenAPI spec types
The types will need to be adapted to make use of the OpenAPI spec.

We can make use of my package [`@wolfy1339/openapi-webhooks-types`](https://github.com/wolfy1339/openapi-webhooks) to help with the transition.

---
Some points which I see as potential issues:

The types format is not the same, the webhooks are not on their own interface like they are currently in [`@octokit/webhooks-types`](https://github.com/octokit/webhooks).
In the OpanAPI spec types, the way to get a webhook resembles like so:
```ts
import { webhooks } from `@wolfy1339/openapi-webhooks-types`;

type TEventIdentifier = "check-suite-completed";
type CheckSuiteCompletedEvent = webhooks[TEventIdentifier]["post"]["requestBody"]["content"]["application/json"];
```
Each webhook definition's name is made like so in reference to the names we accept in the event handlers
```js
const webhookIdentifier = "check_suite.completed".replaceAll(/_|\./g, "-");
// webhookIdentifier: check-suite-completed
```
The name is seperated by `-` and dots are replaced by `-`

<br><br>

There are currently no types for events and all their possible actions, eg: `check_suite`.

I'm not sure how we can get around this easily without having to resort to a lookup table. If you have any ideas, please comment

### PR DESCRIPTION
**Pull request by wolfy1339**
Resolves #840

----

### Before the change?

* The types were made in house by using example payloads and extrapolated a schema from them

### After the change?

* The types use the official GitHub OpenAPI spec

### Other information

*

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [x] Yes (Please add the `Type: Breaking change` label)
- [ ] No

If `Yes`, what's the impact:

* Since we are switching the source of the types, I feel it better to release this as a breaking change

### Pull request type

Please add the corresponding label for change this PR introduces:
- Feature/model/API additions: `Type: Feature`

----

### CODE REVIEW

**Comment by ollie-iterators** [comment]
Some errors:

Error: test/typescript-validate.ts(106,7): error TS2578: Unused '@ts-expect-error' directive.

Also some from the types.d.ts about the property "webhook-check-run-created-form-encoded" not existing on a type

**Comment by wolfy1339** [comment]
I am aware of the errors.

> Error: test/typescript-validate.ts(106,7): error TS2578: Unused '@ts-expect-error' directive.

This is due to https://github.com/github/rest-api-description/issues/2465
The test is supposed to error in normal circumstances, and the error is ignored.

> Also some from the types.d.ts about the property "webhook-check-run-created-form-encoded" not existing on a type

That has been fixed. https://github.com/wolfy1339/openapi-webhooks/commit/01457e3f43260267ea2597778177c920ce5d6952

I haven't updated this PR

**Comment by ollie-iterators** [comment]
Great

**Comment by wolfy1339** [comment]
The webhooks OpenAPI spec has been out for a year now.

The schemas (excluding enum values) are pretty much the same. I have noticed in many areas where they don't change the `enum` according to the `action`.

Overall it would be nice to have people test this package with the OpenAPI webhooks spec

**Comment by wolfy1339** [comment]
@oscard0m @gr2m @G-Rath  I'd like to get your input on this

**Review by gr2m — APPROVED** [review]
I looked through the changes and it looks great, thank you for putting in all this work! When we ship it, shall we move @wolfy1339/openapi-webhooks-types and @wolfy1339/openapi-webhooks to @octokit as well?

**Comment by wolfy1339** [comment]
> I looked through the changes and it looks great, thank you for putting in all this work! When we ship it, shall we move @wolfy1339/openapi-webhooks-types and @wolfy1339/openapi-webhooks to @octokit as well?

Yes, that was the goal

**Comment by wolfy1339** [comment]
I am coming around to this PR again, I have created https://github.com/wolfy1339/openapi-webhooks/issues/80 to track the move to the Octokit org.

I don't have the permissions to move the repo myself, so whomever is available that can do it @kfcampbell @gr2m @nickfloyd

**Pull request merged**
