### PR TITLE
fix(intellisense): intellisense for array arg in `on`

### LINKED ISSUE #140: No intellisense when `on` has an array for event names
This is an awesome lib. Intellisense works great handling single events but when the argument is an array it doesn't show.

### PR DESCRIPTION
**Pull request by ankeetmaini**
Fix #140

### CODE REVIEW

**Comment by oscard0m** [comment]
Hi @ankeetmaini ! Thanks for contributing to this project. Intellisense is awesome. To make it work 100% for octokit users is a game changer in developer's experience. If we get this fixed will be awesome :)

## 💬 Feedback:

✅ Tested copy-pasting the `index.d.ts` in a dummy project and now it shows the events 🎉 :

### Before
image

### After
image

---

❓ With this change I see we lose support for use the same `eventHandler` for different `event types` -> i.e.:

this works because these are events from the same "_event suite_"
```typescript
webhooks.on(["check_run", "check_run.completed"], ({ name }) => {
    console.log(name, "event received");
})
```

this does not work because are events from different "_event suites_"
```typescript
webhooks.on(["check_run", "label.edited"], ({ name }) => {
    console.log(name, "event received");
})
```
image

I think we should keep compatibility for this use case but let's see what @gr2m thinks about it.

---

**Extra ball:** On [this](https://github.com/octokit/webhooks.js/pull/113) pull request it is planned to cover your use case and split the type declaration in several files to have a better structure. Maybe you are interested on following it up or even participate on it.

**Comment by oscard0m** [comment]
Also, I would say to wait to land these fixes which will give back stability to `index.d.ts`. Do you think it would have sense @ankeetmaini  

* https://github.com/octokit/webhooks.js/pull/137
* https://github.com/octokit/webhooks.js/pull/139

**Comment by ankeetmaini** [comment]
> Also, I would say to wait to land these fixes which will give back stability to `index.d.ts`. Do you think it would have sense @ankeetmaini
> 
> * #137
> * #139

Sure, it can wait till we get these two merged in!

**Comment by ankeetmaini** [comment]
I can try and see if we can keep the same handler usecase. Also if #113 is slated to go in soon, I can close this and help out. :)

**Comment by oscard0m** [comment]
> I can try and see if we can keep the same handler usecase. Also if #113 is slated to go in soon, I can close this and help out. :)

🆒 , if you need help with it let us know :)

**Comment by ankeetmaini** [comment]
@dominguezcelada I've removed all the hardcoded overloads and used conditional types to store the mapping of `type -> Payload`. I also added the same signature for `removeListener` which now adds intellisense to it.

> Intellisense works great for array params (likewise for `on`)
Screenshot 2020-05-17 at 4 12 56 PM

> it calculates the payload types
Screenshot 2020-05-17 at 4 14 51 PM

**Comment by gr2m** [comment]
> I think we should keep compatibility for this use case but let's see what @gr2m thinks about it.

I agree but this is better than what we have now. 

@dominguezcelada PR looks good to me if you think it's good. We can iterate on details

**Comment by oscard0m** [comment]
@ankeetmaini nice job doing the type generation more generic with conditional types.

PR's fixing `index.d.ts` are on master already. 

An idea that came in my mind is to extend `typescript-validate.ts` test adding the following cases to double check your changes are keeping retrocompatibility:

`webhooks.on("check_run.completed", () => {})`
`webhooks.on(["check_run.comppleted", "check_run.created"], () => {})`
`webhooks.on(["check_run.comppleted", "commit_comment"], () => {})`

And for
`webhooks.removeListener()`

If you need help with it, let me know :)

**Comment by ankeetmaini** [comment]
@dominguezcelada I've added the changes for validating type fixes. Let me know if something more needs to be done!

**Review by oscard0m — APPROVED** [review]

**Comment by oscard0m** [comment]
> @dominguezcelada I've added the changes for validating type fixes. Let me know if something more needs to be done!

Amazing Job @ankeetmaini. Tried it in a dummy repo and works good to me :)

**Pull request merged**
