### PR TITLE
ci: stop testing against NodeJS v14, v16

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: Drop support for NodeJS v14, v16

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
I think I'd remove both node 14 and node 16. Node 16 is nearly out of maintenance: https://nodejs.dev/en/about/releases/. If anyone complaints, they can still use the older versions and we can still accept patches for older versions. That will save us another breaking change release within a few months

Also when doing breaking changes, I'd always look for deprecations and remove them as well.

/cc @octokit/js

**Comment by wolfy1339** [comment]
> I think I'd remove both node 14 and node 16. Node 16 is nearly out of maintenance: https://nodejs.dev/en/about/releases/.

I hadn't really thought of Node 16

> If anyone complaints, they can still use the older versions and we can still accept patches for older versions. That will save us another breaking change release within a few months

Good point. I'll update my octoherd script and run it again with these changes

**Comment by G-Rath** [comment]
Inversely: why are we dropping support for v14? I know that it'll mean we might not have to transpile as much, but I wouldn't expect the wins to be that great so unless there's a particular feature or dependency we know we can be using with v14/v16, or there's another breaking change we want to land (which might be #841?), is there a good reason to drop support for these versions?

**Comment by wolfy1339** [comment]
We will still support those versions with bug fixes for the near future.

Dropping support means easier transition to ESM, and no need to keep polyfills for the fetch API.

It just doesn't make much sense to support versions that are EOL

There was a discussion around this briefly, https://github.com/orgs/octokit/discussions/21

**Comment by G-Rath** [comment]
> We will still support those versions with bug fixes for the near future.

In that case we should be testing against them? You either are or are not supporting the versions right? 🙂

> There was a discussion around this briefly, https://github.com/orgs/octokit/discussions/21

It doesn't look like anything was ever actually agreed from that discussion - I've posted a comment with my thoughts on it.

**Comment by wolfy1339** [comment]
> In that case we should be testing against them? You either are or are not supporting the versions right? :slightly_smiling_face:

As gr2m said, we can support them with patches in maintenance releases. In the current release, we won't be supporting them
> If anyone complaints, they can still use the older versions and we can still accept patches for older versions.

**Review by kfcampbell — DISMISSED** [review]

**Comment by nickfloyd** [comment]
https://github.com/orgs/octokit/discussions/44

**Review by kfcampbell — APPROVED** [review]

**Pull request merged**
