### PR TITLE
fix(typescript): Properly fix #64

### LINKED ISSUE #64: Readme Example Fails to Compile with TypeScript
Hello! I attempted to build a new TypeScript project that consumes this module. I created a `package.json` and installed the following dependencies:
```json
{
  "dependencies": {
    "@octokit/webhooks": "5.3.3"
  },
  "devDependencies": {
    "@types/node": "^11.12.0",
    "typescript": "^3.3.4000"
  }
}
```

I took the example from the readme and fixed the imports to work with TypeScript but it fails to compile:
```ts
// TypeScript default import syntax
import * as WebhooksApi from '@octokit/webhooks';
import * as http from 'http';

const webhooks = new WebhooksApi({
  secret: 'mysecret'
});

webhooks.on('*', ({id, name, payload}) => {
  console.log(name, 'event received');
});

http.createServer(webhooks.middleware).listen(3000);
//                ~~~~~~~~~~~~~~~~~~~
// TS2559: Type '(request: ClientRequest, response: ServerResponse, next: (err?: any) => void) => (request: IncomingMessage, response: ServerResponse) => void' has no properties in common with type 'ServerOptions'.
```

I would expect that this code example would successfully compile. What is going on here? It looks like `middleware` is not a `http.RequestListener`, but a function that returns a `http.RequestListener`. Is this merely an issue with the definition of `middleware` in `index.d.ts`? 

Thanks for your help!

### PR DESCRIPTION
**Pull request by wolfy1339**
I had totally forgot about it. I'm used to having a template file lie other repositories xD

### CODE REVIEW

**Comment by gr2m** [comment]
> I'm used to having a template file lie other repositories

what do you mean?

**Review by gr2m — APPROVED** [review]
Looks good to me 👍

**Comment by gr2m** [comment]
you want to wait for https://github.com/octokit/webhooks.js/pull/69 or shall I merge this in?

**Comment by wolfy1339** [comment]
Better to merge this now

**Comment by wolfy1339** [comment]
> 
> 
> > I'm used to having a template file lie other repositories
> 
> what do you mean?

Like this file in the `@octokit/rest` repo: https://github.com/octokit/rest.js/blob/master/scripts/templates/index.d.ts.tpl

**Comment by gr2m** [comment]
There is [scripts/generate-types.js](https://github.com/octokit/webhooks.js/blob/master/scripts/generate-types.js) and a warning on top of the file
https://github.com/octokit/webhooks.js/blob/245c40d3f0c218a5a18db905415fa923c5a2a7f7/index.d.ts#L1-L2

:)

**Comment by gr2m** [comment]
I think we had the idea to split the `index.d.ts` into a static part we can edit and a generated one that is clearly declared as such, e.g. by living in a path such as `/generated/definitions.d.ts`, then import `generated/definitions` in index.d.ts?

**Pull request merged**
