### PR TITLE
merge next

### PR DESCRIPTION
**Pull request by oscard0m**
- build: delete the `pkg` folder to start with a clean slate
- build: don't include `node_modules` in bundles
- build: use `index.js` as the sole bundle entry point
- build: use `fs.rm()` instead of `fs.rmDir()`
- build: delete the `type.js` files
- build: optimise glob usage
- style: run prettier
- build: also remove map files
- build: add comments to the build script
- Update scripts/build.ts
- build: use `Promise.all()`
- build: use Promise api for `fs` modules
- build: switch to async glob
- build: switch to plain JS file
- chore: update `.gitignore` comment
- build: fix script in `package.json`
- build: reduce glob expression
- build: don't use `./` in paths in `package.json`
- Update scripts/build.mjs
- Update scripts/build.mjs
- Apply suggestions from code review
- style: run prettier
- fix: empty commit to trigger release
- fix(build): serve types from dist-types/index.d.ts
- fix(build): include sourceContent in node/browser bundles

### CODE REVIEW

**Review by wolfy1339 — DISMISSED** [review]

**Comment by oscard0m** [comment]
Wait, I'm missing one commit 🤦🏽 It should be 26 commits, not 25

**Comment by wolfy1339** [comment]
We won't be able to do a squash or rebase in order to keep the correct commit information for semantic release.

A basic merge will have to be done

**Comment by oscard0m** [comment]
> We won't be able to do a squash or rebase in order to keep the correct commit information for semantic release.
> 
> A basic merge will have to be done

How? the branch is protected

**Review by wolfy1339 — APPROVED** [review]

**Comment by wolfy1339** [comment]
You can use pull requests.

We just can't use the squash or rebase merge options

**Comment by oscard0m** [comment]
> You can use pull requests.
> 
> We just can't use the squash or rebase merge options

Do you know how?

image

**Comment by wolfy1339** [comment]
That would require an admin to do this :/

@kfcampbell @nickfloyd @gr2m Can one of you help us out 🙏

**Pull request closed without merging**
