### PR TITLE
feat(types): add new events via `@octokit/webhooks-schemas` update to `v7.4.0`

### PR DESCRIPTION
**Pull request by harryzcy**
Resolves #ISSUE_NUMBER

----

### Before the change?

Update `@octokit/webhooks-types` for v12.x

### After the change?

* 

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by wolfy1339** [comment]
Please also update `@octokit/webhooks-schemas`

And run
```
npm run generate-types
```

**Comment by harryzcy** [comment]
> Please also update `@octokit/webhooks-schemas`
> 
> And run
> 
> ```
> npm run generate-types
> ```

Thanks, updated

**Review by wolfy1339 — APPROVED** [review]

**Comment by harryzcy** [comment]
@wolfy1339 It seems that `push-payload.json` need to be updated. How can I find the correct test fixture?

**Comment by wolfy1339** [comment]
You can copy the one from the `main` branch and it'll pass validation

**Comment by harryzcy** [comment]
~It looks like `push-payload.json` from `main` doesn't have `custom_properties` as well~

@wolfy1339 Thanks

**Comment by wolfy1339** [comment]
> It looks like `push-payload.json` from `main` doesn't have `custom_properties` as well

I saw that. It seems like the property is maybe not always present. :man_shrugging:

**Comment by wolfy1339** [comment]
The release is currently blocked by #991

**Pull request merged**
