### PR TITLE
📦 refactor(library): migrate  entry point of all modules to lib/index.js

### PR DESCRIPTION
**Pull request by oscard0m**
## 📝 Summary

- Change entry point for all modules to `lib/index.js`
- Keep retrocompatibility but warn the user about a future deprecation

## ⛱ Motivation and Context

https://github.com/octokit/webhooks.js/pull/113

### CODE REVIEW

**Comment by gr2m** [comment]
When I run the tests, I only see one message

> src/verify/index.js is deprecated. Use lib/index.js instead.

I'd expect to log messages for all the module imports?

Also the message should clarify that it's about the `require` statement, maybe something like this?

> `const verify = require('@octokit/webhooks/verify')` is deprecated. Use `const { verify } = require('@octokit/webhooks')` instead

The tests should test for dedeprecations. I'd make a separate `test/integration/deprecations-test.ts` file which only does the now deprecated import. You can use `simple-mock` to test that the correct message was logged. Once that is all working, you can adapt the existing tests in the other files to remove the deprecation messages by using the new import

**Comment by oscard0m** [comment]
> When I run the tests, I only see one message
> 
> > src/verify/index.js is deprecated. Use lib/index.js instead.
> 
> I'd expect to log messages for all the module imports?

Let me take a look

> Also the message should clarify that it's about the `require` statement, maybe something like this?
> 
> > `const verify = require('@octokit/webhooks/verify')` is deprecated. Use `const { verify } = require('@octokit/webhooks')` instead

I like it. Sounds good to me to clarify the named export way we are migrating to.

> The tests should test for dedeprecations. I'd make a separate `test/integration/deprecations-test.ts` file which only does the now deprecated import. You can use `simple-mock` to test that the correct message was logged. Once that is all working, you can adapt the existing tests in the other files to remove the deprecation messages by using the new import

👌 To add `deprecations-tests` (.js for the moment I guess)
👌 To adapt existing smoke-test to use new imports

**Comment by oscard0m** [comment]
🚑 Applied major fix (the previous changes were completely wrong)
☑️ Applied improvement on deprecation message
☑️ Adapted `test/integration/smoke-test.js` to use new exposed entries
☑️ Created `test/integration/deprecation-test` to assure there is retrocompatibility

---

⚠️ It seems that `tap` is hidding under the carpet the depreation warnings:
> npx tap test/integration/deprecation-test.js
image

🆚 
> node test/integration/deprecation-test.js
image

Also tested manually creating dummy js files and running them with node. i.e.:

```javascript
const verify = require("./src/verify");
verify("1234", {}, "randomSignature")
```

image

---

I've been researching a way to make `tap` output the deprecation warning message but I did not find a way. Do you know a way maybe?

Thanks @gr2m

**Comment by gr2m** [comment]
You do a great job splitting up your work in meaningful commits, makes it a joy to review your changes 👍 

> I've been researching a way to make tap output the deprecation warning message but I did not find a way. Do you know a way maybe?

I would mock `process.emitWarning` the way we currently do here:

https://github.com/octokit/webhooks.js/blob/d675137b32c5867c3fe5f1d204a8075b85cb83d1/test/unit/event-handler-on-test.js#L13

The function `simple.mock` returns a `mock` object, which you can use for asserts, e.g. 

```js
const mock =   simple.mock(process, "emitWarning").callFn(function () {});
// ...
t.equals(mock.callCount, 1)
```

I _think_ that should work 😁

**Comment by oscard0m** [comment]
> You do a great job splitting up your work in meaningful commits, makes it a joy to review your changes 👍

Thanks for the compliment @gr2m 😍 

> > I've been researching a way to make tap output the deprecation warning message but I did not find a way. Do you know a way maybe?
> 
> I would mock `process.emitWarning` the way we currently do here:
> 
> https://github.com/octokit/webhooks.js/blob/d675137b32c5867c3fe5f1d204a8075b85cb83d1/test/unit/event-handler-on-test.js#L13
> 
> The function `simple.mock` returns a `mock` object, which you can use for asserts, e.g.
> 
> ```js
> const mock =   simple.mock(process, "emitWarning").callFn(function () {});
> // ...
> t.equals(mock.callCount, 1)
> ```
> 
> I _think_ that should work 😁

Let me give it a try!

**Comment by oscard0m** [comment]
> Let me give it a try!

It works! @gr2m 🤓 🍾

**Review by gr2m — APPROVED** [review]
great work 👍  I've tested it against latest `probot` and it still all works

**Comment by oscard0m** [comment]
> great work 👍 I've tested it against latest `probot` and it still all works

Thanks once again :)

**Pull request merged**
