### PR TITLE
fix(typescript): add types for `check_run.requested_action`

### PR DESCRIPTION
**Pull request by codebytere**
Bump `@octokit/webhooks-definitions` to pick up https://github.com/octokit/webhooks/pull/222 and fix missing `requested_action?: WebhookPayloadCheckRunRequestedAction;` in `WebhookPayloadCheckRun`

cc @gr2m

### CODE REVIEW

**Review by gr2m — CHANGES_REQUESTED** [review]
Thanks! I should automate this update so we don't need to wait for Dependabot to do its thing over night.

You need to run `npm run generate-types` to update the TypeScript definitions and push the change. I wanted to do the update for you but I cannot push to your fork repository, it's shown as "unknown repository"?

**Comment by codebytere** [comment]
@gr2m oops yep i'll fix it, one sec!

**Comment by codebytere** [comment]
Open at https://github.com/octokit/webhooks.js/pull/370

**Comment by oscard0m** [comment]
> I should automate this update so we don't need to wait for Dependabot to do its thing over night.

Do you want me to create an issue for this? @gr2m :)

**Comment by gr2m** [comment]
Thanks, already done via https://github.com/octokit/webhooks.js/commit/f1d9c485420fdd0e39814a2cf134cd0c2cf7cacc :)

**Pull request closed without merging**
