### PR TITLE
Explicitly specify that TS 4.1 is required

### PR DESCRIPTION
**Pull request by jstastny**
The compilation under TypeScript 4.0 fails.

```
$ npm install typescript@4.0
$ npm run validate:ts


> @octokit/webhooks@0.0.0-development validate:ts /Users/honza/projects/webhooks.js
> tsc --noEmit --noImplicitAny --target es2020 --esModuleInterop --moduleResolution node test/typescript-validate.ts

src/types.ts:12:27 - error TS1110: Type expected.

12 > = TEmitterEvent extends `${infer TWebhookEvent}.${infer TAction}`
                             ~~~

src/types.ts:12:36 - error TS1005: '}' expected.

12 > = TEmitterEvent extends `${infer TWebhookEvent}.${infer TAction}`
                                      ~~~~~~~~~~~~~

src/types.ts:12:49 - error TS1128: Declaration or statement expected.

12 > = TEmitterEvent extends `${infer TWebhookEvent}.${infer TAction}`
                                                   ~

src/types.ts:12:50 - error TS1128: Declaration or statement expected.

12 > = TEmitterEvent extends `${infer TWebhookEvent}.${infer TAction}`
                                                    ~

src/types.ts:12:52 - error TS1005: ';' expected.

12 > = TEmitterEvent extends `${infer TWebhookEvent}.${infer TAction}`
                                                      ~

src/types.ts:12:59 - error TS1005: ';' expected.

12 > = TEmitterEvent extends `${infer TWebhookEvent}.${infer TAction}`
                                                             ~~~~~~~

src/types.ts:53:55 - error TS1005: ';' expected.

53  * Error object with optional properties coming from `octokit.request` errors
                                                         ~~~~~~~

src/types.ts:77:1 - error TS1160: Unterminated template literal.

77



Found 8 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @octokit/webhooks@0.0.0-development validate:ts: `tsc --noEmit --noImplicitAny --target es2020 --esModuleInterop --moduleResolution node test/typescript-validate.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @octokit/webhooks@0.0.0-development validate:ts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

I am not sure if the `package-json.lock` should be modified as well or not. I have modified it to match the minimum required version and therefore make the continuous integration run on that version, which is IMO an advantage.

### CODE REVIEW

**Review by gr2m — DISMISSED** [review]

**Comment by wolfy1339** [comment]
`package-lock.json` currently (on master branch) contains version 4.2.2 of TypeScript, can you revert that change since it isn't necessary

**Comment by jstastny** [comment]
> `package-lock.json` currently (on master branch) contains version 4.2.2 of TypeScript, can you revert that change since it isn't necessary

Yeah. I've seen that. I was not sure if you wanted to keep that newer (4.2.2) version in the lock and effectively run the tests on something newer that the lowest supported (4.1), which could lead to similar situation as this PR is trying to fix -- the this package uses features that are not available in Typescript declared in `package.json`.

**Comment by wolfy1339** [comment]
That is a good point.
That would be a follow up issue to program CI to test against the supported versions of TS

**Comment by jstastny** [comment]
Meaning I should still revert the lock file in this PR, correct?

**Comment by wolfy1339** [comment]
Yes, please do

**Comment by jstastny** [comment]
Ok. Done.

**Review by wolfy1339 — APPROVED** [review]

**Comment by oscard0m** [comment]
> That is a good point.
> That would be a follow up issue to program CI to test against the supported versions of TS

Created follow up issue: https://github.com/octokit/webhooks.js/issues/486

**Pull request merged**
